//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument may not contain an empty collection!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgEmptyCollection {
            get {
                return ResourceManager.GetString("Guard_ArgEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be greater than  {0}!\r\n[called from {1} in {2}, line {3}].
        /// </summary>
        internal static string Guard_ArgGreaterThan {
            get {
                return ResourceManager.GetString("Guard_ArgGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must contain at least one element!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgIsEmpty {
            get {
                return ResourceManager.GetString("Guard_ArgIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not be FALSE!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgIsFalse {
            get {
                return ResourceManager.GetString("Guard_ArgIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument contains an invalid date-time value!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgIsInvalidDateTime {
            get {
                return ResourceManager.GetString("Guard_ArgIsInvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not be TRUE!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgIsTrue {
            get {
                return ResourceManager.GetString("Guard_ArgIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument may not contain a zero time span!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgIsZero {
            get {
                return ResourceManager.GetString("Guard_ArgIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not be less than {0}!\r\n[called from {1} in {2}, line {3}].
        /// </summary>
        internal static string Guard_ArgLessThan {
            get {
                return ResourceManager.GetString("Guard_ArgLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must contain a value &gt; 0!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgLessThanEqualZero {
            get {
                return ResourceManager.GetString("Guard_ArgLessThanEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must contain a value &lt; 0!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgLessThanZero {
            get {
                return ResourceManager.GetString("Guard_ArgLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must contain an empty collection!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgNotEmptyCollection {
            get {
                return ResourceManager.GetString("Guard_ArgNotEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be null or empty!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Guard_ArgNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is not a readable stream!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgNotReadable {
            get {
                return ResourceManager.GetString("Guard_ArgNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is not a writable stream!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgNotWritable {
            get {
                return ResourceManager.GetString("Guard_ArgNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must contain a zero!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgNotZero {
            get {
                return ResourceManager.GetString("Guard_ArgNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument contains a null!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgNull {
            get {
                return ResourceManager.GetString("Guard_ArgNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument may not be null or empty!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgNullOrEmpty {
            get {
                return ResourceManager.GetString("Guard_ArgNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument may not contain a zero!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_ArgZero {
            get {
                return ResourceManager.GetString("Guard_ArgZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument may not contain an empty GUID!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_EmptyGuid {
            get {
                return ResourceManager.GetString("Guard_EmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument contains an invalid file extension!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_InvalidExtension {
            get {
                return ResourceManager.GetString("Guard_InvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument contains an invalid file path!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_InvalidFilePath {
            get {
                return ResourceManager.GetString("Guard_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument contains an invalid folder path!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_InvalidFolderPath {
            get {
                return ResourceManager.GetString("Guard_InvalidFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is not a well formed URI!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_MalformedUri {
            get {
                return ResourceManager.GetString("Guard_MalformedUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument should contain an empty GUID!\r\n[called from {0} in {1}, line {2}].
        /// </summary>
        internal static string Guard_NotEmptyGuid {
            get {
                return ResourceManager.GetString("Guard_NotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while iterating over an enumerable sequence! See any inner exception(s) for more details..
        /// </summary>
        internal static string IEnumerableExtensions_ForEach {
            get {
                return ResourceManager.GetString("IEnumerableExtensions_ForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not have a public property named &apos;{1}&apos;!.
        /// </summary>
        internal static string PropertyCache_NotFound {
            get {
                return ResourceManager.GetString("PropertyCache_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cache key information for the property &apos;{1}&apos; on type &apos;{0}&apos;!.
        /// </summary>
        internal static string PropertyCache_UnableToCache {
            get {
                return ResourceManager.GetString("PropertyCache_UnableToCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create type: {0} as a singleton.
        /// </summary>
        internal static string SingletonBaseEx_Instance {
            get {
                return ResourceManager.GetString("SingletonBaseEx_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} validation error! Error: {1}, Members: {2}.
        /// </summary>
        internal static string VerifiableObject_Invalid {
            get {
                return ResourceManager.GetString("VerifiableObject_Invalid", resourceCulture);
            }
        }
    }
}
